#
server:
  port: 9000
#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-spring-security
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    check-template-location: true
    encoding: UTF-8
    #用非严格的HTMl
    mode: HTML5
    servlet:
      content-type: text/html
