#
server:
  port: 9000

#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-spring-security
  thymeleaf:
    #开发时关闭缓存,不然没法看到实时页面
    cache: false
    prefix: classpath:/templats
    suffix: .html
    #用非严格的HTMl
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template: true
