#
server:
  port: 9000

#
logging:
  config: classpath:logback.xml
#
spring:
  application:
    name: study-spring-security
  thymeleaf:
    cache: false
    prefix: classpath:/templats
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    check-template: true
